export const PERMISSIONS = {
    CREATE_FORM: 'CREATE_FORM',
    EDIT_FORM: 'EDIT_FORM',
    DELETE_FORM: 'DELETE_FORM',
    PUBLISH_FORM: 'PUBLISH_FORM',
    MANAGE_CENTERS: 'MANAGE_CENTERS',
    CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
    MANAGE_USERS: 'MANAGE_USERS',
    VIEW_REPORTS: 'VIEW_REPORTS'
};
